//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 78,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 66,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 2,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 58,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 9,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 8,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 86,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 27,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 30,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 63,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 88,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 51,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 37,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 74,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 49,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 1 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 22 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 77 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 39 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 77 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.53,
          weight: 0.8,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2024-07-27T12:36:46.126Z',
          stock: 1,
          id: 53,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.7,
          weight: 0.54,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2023-10-08T08:07:52.615Z',
          stock: 2,
          id: 8,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.63,
          weight: 0.28,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2025-01-24T17:48:29.228Z',
          stock: 3,
          id: 49,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 0.45,
          weight: 0.54,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2023-10-17T08:22:46.076Z',
          stock: 4,
          id: 59,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.78,
          weight: 0.22,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2024-04-08T12:09:13.492Z',
          stock: 5,
          id: 71,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 25 },
        { category: 'category 2', id: 27 },
        { category: 'category 3', id: 48 },
        { category: 'category 4', id: 16 },
        { category: 'category 5', id: 64 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.98,
          discountPercent: 0.65,
          id: 67,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.92,
          discountPercent: 0.83,
          id: 37,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.32,
          discountPercent: 0.41,
          id: 51,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 0.38,
          discountPercent: 0.14,
          id: 52,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.4,
          discountPercent: 0.64,
          id: 98,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.97, quantity: 1, id: 46 },
        { customer: 2, product: 2, priceAtPurchase: 0.68, quantity: 2, id: 88 },
        { customer: 3, product: 3, priceAtPurchase: 0.1, quantity: 3, id: 20 },
        { customer: 4, product: 4, priceAtPurchase: 0.64, quantity: 4, id: 74 },
        { customer: 5, product: 5, priceAtPurchase: 0.47, quantity: 5, id: 86 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.06,
          vat: 0.43,
          totalAmountWithVat: 0.96,
          shippingCost: 0.48,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2024-10-04T14:36:14.887Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 39,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.61,
          vat: 0.66,
          totalAmountWithVat: 0.97,
          shippingCost: 0.96,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2023-08-15T00:59:08.170Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 47,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.09,
          vat: 0.95,
          totalAmountWithVat: 0.7,
          shippingCost: 0.32,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2023-10-22T05:43:11.377Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 91,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.47,
          vat: 0.59,
          totalAmountWithVat: 0.76,
          shippingCost: 0.73,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2024-12-15T07:53:01.520Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 87,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.85,
          vat: 0.74,
          totalAmountWithVat: 0.19,
          shippingCost: 0.49,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2023-12-19T13:51:31.768Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 90,
        },
      ],
      OrderDetails: [
        {
          orderNumber: 1,
          line: 1,
          product: 1,
          price: 0.35,
          quantity: 1,
          id: 27,
        },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.01,
          quantity: 2,
          id: 85,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.18,
          quantity: 3,
          id: 13,
        },
        {
          orderNumber: 4,
          line: 4,
          product: 4,
          price: 0.51,
          quantity: 4,
          id: 78,
        },
        {
          orderNumber: 5,
          line: 5,
          product: 5,
          price: 0.17,
          quantity: 5,
          id: 84,
        },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2024-05-16T00:20:31.773Z',
          paymentStatus: 'paymentStatus 1',
          id: 37,
        },
        {
          orderNumber: 2,
          amount: 0.86,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2024-09-25T07:32:08.123Z',
          paymentStatus: 'paymentStatus 2',
          id: 30,
        },
        {
          orderNumber: 3,
          amount: 0.35,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2024-04-19T18:18:40.858Z',
          paymentStatus: 'paymentStatus 3',
          id: 9,
        },
        {
          orderNumber: 4,
          amount: 0.98,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2024-03-18T03:09:55.147Z',
          paymentStatus: 'paymentStatus 4',
          id: 4,
        },
        {
          orderNumber: 5,
          amount: 0.52,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2025-01-19T17:06:05.244Z',
          paymentStatus: 'paymentStatus 5',
          id: 57,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 1,
          reviewDetails: 'reviewDetails 1',
          date: '2023-12-04T03:44:48.090Z',
          id: 66,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.59,
          reviewDetails: 'reviewDetails 2',
          date: '2023-05-24T04:05:12.088Z',
          id: 94,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.45,
          reviewDetails: 'reviewDetails 3',
          date: '2024-07-26T21:40:47.535Z',
          id: 26,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.7,
          reviewDetails: 'reviewDetails 4',
          date: '2024-06-25T16:17:31.288Z',
          id: 100,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0,
          reviewDetails: 'reviewDetails 5',
          date: '2024-09-25T09:45:44.217Z',
          id: 84,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2024-03-06T12:55:36.286Z',
          resolutionDate: '2023-08-10T23:49:48.270Z',
          id: 68,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-05-13T12:07:07.971Z',
          resolutionDate: '2024-01-16T05:34:31.575Z',
          id: 33,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2024-07-27T00:45:55.340Z',
          resolutionDate: '2023-07-14T18:00:09.538Z',
          id: 12,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-03-07T20:22:17.393Z',
          resolutionDate: '2024-11-02T18:09:24.128Z',
          id: 44,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2024-01-23T12:55:03.895Z',
          resolutionDate: '2024-10-06T22:29:03.512Z',
          id: 18,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
